version: "3"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - ${PWD}/var/lib/mysql:/var/lib/mysql

  cache:
    image: redis:alpine
    restart: always
    volumes:
      - ${PWD}/var/lib/redis:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  proxy:
    image: nginx:latest
    restart: always
    volumes:
      - ${PWD}/etc/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/var/run:/var/run
      - ${PWD}/var/log/nginx:/var/log/nginx
    ports:
      - "8000:80"
    command: ["nginx", "-g", "daemon off;"]

  web:
    build: .
    image: django:v1
    restart: always
    volumes:
      - ${PWD}/src:/home/test/src
      - ${PWD}/var/run:/home/test/var/run
      - ${PWD}/var/log:/home/test/var/log
    # ports:
    #  - "8080-8090:8080"
    # command: ["python", "manage.py", "runserver", "0.0.0.0:8080", "--noreload"]
    depends_on:
      - db
      - cache

  cron:
    build: .
    image: django:v1
    restart: always
    volumes:
      - ${PWD}/src:/home/test/src
      - ${PWD}/var/log:/home/test/var/log
    command: ["cron"]
    depends_on:
      - db
      - cache

volumes:
  uwsgi_socket:
