version: "3"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - ${PWD}/var/lib/mysql:/var/lib/mysql

  web:
    build: .
    restart: always
    command: python manage.py runserver "0.0.0.0:8000"
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
